### PR TITLE
Added GetList method for getting list(s) containing contacts

### PR DESCRIPTION
**Pull request by vindevries**
Added GetList method for getting list(s) containing contacts

### CODE REVIEW

**Comment by Psypher9** [comment]
Thank you for your PR and your first one at that! I'm going to review this and get back with you soon.

We are currently developing on our `v1-preview` branch so I may merge it there. Be looking for my feedback!

**Comment by Psypher9** [comment]
I haven't forgotten about you @vindevries! Thank you for your patience!

**Comment by vindevries** [comment]
No Worries, Just happy to make a small contribution.

**Review by Psypher9 — COMMENTED** [review]
I think these are looking good. Going to see if I can resolve the conflicts now.

**Comment by Psypher9** [comment]
Thank you @vindevries! ...1 year later... i know...

**Pull request merged**
